apiVersion: v1
kind: Namespace
metadata:
  name: fullstack-monolith-prod
  labels:
    name: fullstack-monolith-prod
    environment: production
    project: fullstack-monolith
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
    environment: production
    project: fullstack-monolith
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
  labels:
    name: ingress-nginx
    environment: production
    project: fullstack-monolith
